name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # Get your code
    - name: Checkout
      uses: actions/checkout@v4

    # Install system packages
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17 unzip git

    # Install Buildozer
    - name: Install Buildozer
      run: pip install --upgrade pip buildozer

    # Initialize buildozer
    - name: Init Buildozer
      run: buildozer init

    # Configure requirements
    - name: Configure buildozer
      run: |
        sed -i 's/requirements =.*/requirements = python3,kivy,plyer,requests/' buildozer.spec

    # Build APK
    - name: Build APK
      run: buildozer android debug

    # Upload APK (NEW VERSION v4)
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
