name: Build APK (python-for-android)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # ⚠️ 24.04 avoid pannrom (more stable)

    steps:

    # 1. Checkout
    - name: Checkout
      uses: actions/checkout@v4


    # 2. Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"


    # 3. Java
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17


    # 4. System packages
    - name: Install Packages
      run: |
        sudo apt update
        sudo apt install -y \
          git zip unzip \
          build-essential \
          libssl-dev libffi-dev \
          libsqlite3-dev \
          zlib1g-dev \
          openjdk-17-jdk


    # 5. Install python-for-android
    - name: Install p4a
      run: |
        pip install --upgrade pip
        pip install python-for-android cython


    # 6. Setup Android SDK
    - name: Setup Android SDK
      run: |

        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk

        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools-linux-*.zip

        mkdir -p cmdline-tools/latest
        mv cmdline-tools/* cmdline-tools/latest/ || true

        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

        yes | cmdline-tools/latest/bin/sdkmanager --licenses

        cmdline-tools/latest/bin/sdkmanager \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2" \
          "ndk;25.2.9519653"


    # 7. Build APK using p4a
    - name: Build APK
      run: |

        p4a apk \
          --private . \
          --package com.shadow.bridge \
          --name "ShadowBridge" \
          --version 0.1 \
          --bootstrap sdl2 \
          --requirements python3,kivy,requests,plyer \
          --sdk-dir $ANDROID_HOME \
          --ndk-dir $ANDROID_HOME/ndk/25.2.9519653 \
          --arch arm64-v8a \
          --permission INTERNET \
          --release


    # 8. Upload APK
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-apk
        path: dist/*.apk
